backstage/urls.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  2:32 下午
# @File    : urls.py
# @Software: PyCharm
from django.urls import path,include
from .views import *
app_name = 'backstage'
urlpatterns = [
    path('',index,name='index'),
    path('create_task/',create_task,name='create_task'),
    path('task_control/',task_control,name='task_control'),
    path('task_control/detial/<id>',task_detial,name='detial'),
    path('task_control/delate/<id>',task_delate,name='delate'),
    path('class_control/',class_control,name='class_control'),
    path('class_control/delate/<id>',delate_class,name='delate_class'),
    path('class_control/detial/<id>',class_detial,name='class_detial'),
    path('class_control/detial/delate/<id>',delate_student,name='delate_student'),
    path('add_student/',add_student,name='add_student'),
    path('add_class/',add_class,name='add_class'),
# path('class_control/delate/<id>',class_delate,name='class_control'),
]

blog/urls.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  9:49 下午
# @File    : urls.py
# @Software: PyCharm
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_index, name='index'),
    path('pub/',article_pub,name='pub_article'),
    path('detial/<pk>',blog_detail,name='detial'),
    path('backstage/',blog_control,name='back'),
]

coding/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from front import urls as furls
from login import urls as lurls
from backstage import urls as burls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(furls,namespace='front')),
    path('',include(lurls,namespace='login')),
    path('back/',include(burls,namespace='backstage')),
    path('captcha/',include('captcha.urls')),
    path('mdeditor/',include('mdeditor.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backstage/models.py
from django.db import models
class Task(models.Model):
    title = models.CharField(max_length=128,null=True)
    descriptions = models.TextField(null=True)
    scripts = models.TextField(null=True)
    c_time = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=128,null=False)

    class Meta:
        db_table = "task"  # 定义表名
        verbose_name = '任务'  # 这个verbose_name是在管理后台显示的名称
        verbose_name_plural = '任务' #复数形式的显示名称
        ordering = ['c_time']  # 排序

    def __str__(self):
        return self.title
class Class(models.Model):
    class_name = models.CharField(max_length=20)
    create_teacher = models.CharField(max_length=10,default=None)
    class Meta:
        db_table = "class"  # 定义表名
        verbose_name = '班级'  # 这个verbose_name是在管理后台显示的名称
        verbose_name_plural = '班级' #复数形式的显示名称

    def __str__(self):
        return self.class_name

backstage/forms.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  3:07 下午
# @File    : forms.py
# @Software: PyCharm
from django import forms


class CreateTask(forms.Form):
    title = forms.CharField(label='标题')
    descriptions = forms.CharField(widget=forms.Textarea,label='题目描述')
    scripts =forms.CharField(widget=forms.Textarea,label='示例代码')

class EditorTask(forms.Form):
    title = forms.CharField(label='标题')
    descriptions = forms.CharField(widget=forms.Textarea, label='题目描述')
    scripts = forms.CharField(widget=forms.Textarea, label='示例代码')

class EditorClass(forms.Form):
    class_name = forms.CharField(label='班级名称')
    max_student = forms.IntegerField(label='班级最大人数')
class Add_student(forms.Form):
    student_name = forms.CharField(label='学生姓名')
class Add_class(forms.Form):
    class_name = forms.CharField(label='班级名称')

backstage/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from login.models import *
def index(request):
    return render(request,'list.html')

def create_task(request):
    if request.method == 'POST':
        task_form = CreateTask(request.POST)
        if task_form.is_valid():
            title = task_form.cleaned_data['title']
            descriptions = task_form.cleaned_data['descriptions']
            scripts = task_form.cleaned_data['scripts']
            same_title = Task.objects.filter(title=title)
            if same_title:
                message = '相同的标题已存在，请重新输入'
                return render(request,'create_task.html',locals())
            else:
                success = '发布成功！请到任务管理界面查看'
                new_task = Task.objects.create()
                new_task.author = request.session.get('user_name')
                new_task.title = title
                new_task.descriptions = descriptions
                new_task.scripts = scripts
                new_task.save()
                return render(request,'create_task.html',locals())
    task_form = CreateTask()
    return render(request,'create_task.html',locals())

def task_control(request):
    task_list =  Task.objects.filter(author=request.session.get('user_name'))
    return render(request,'task_control.html',locals())

def task_detial(request,id):
    task = Task.objects.get(id=id)
    if request.method == 'POST':
        remake_task = CreateTask(request.POST)
        if remake_task.is_valid():
            re_title = remake_task.cleaned_data['title']
            print(re_title)
            re_descriptions = remake_task.cleaned_data['descriptions']
            re_scripts = remake_task.cleaned_data['scripts']
            same_title = Task.objects.filter(title=re_title)
            if same_title:
                message = '相同的标题已存在，请重新输入'
                detial_form = EditorTask(initial={'title': task.title,
                                                  'descriptions': task.descriptions,
                                                  'scripts': task.scripts})
                return render(request,'task_detial.html',locals())
            else:
                success = '修改成功'
                task.title = re_title
                task.descriptions = re_descriptions
                task.scripts = re_scripts
                task.save()
                return render(request,'task_detial.html',locals())
    detial_form = EditorTask(initial={'title':task.title,
                                      'descriptions':task.descriptions,
                                      'scripts':task.scripts})
    return render(request,'task_detial.html',locals())

def task_delate(request,id):
    if request.method == 'POST':
        message = '删除成功,请返回任务列表查看'
        task = Task.objects.get(pk=id)
        task.delete()
    return render(request,'delate_task.html',locals())


def class_control(request):
    class_list = Class.objects.filter(create_teacher = request.session.get('user_name'))
    try:
        del request.session['class_id']
    except :
        pass
    return render(request,'class_control.html',locals())

def class_detial(request,id):
    request.session['class_id'] = id
    student_list = Student.objects.filter(to_class=Class.objects.get(pk=id))
    return render(request,'class_detial.html',locals())

def add_student(request):
    if request.method == 'POST':
        add_form = Add_student(request.POST)
        if add_form.is_valid():
            new_class_student = add_form.cleaned_data['student_name']
            try:
                target_student = Student.objects.get(name=new_class_student)
                if target_student.to_class != None:
                    fail_message = '学生已有班级，增加失败!'
                else:
                    success_message = '添加成功'
                    target_student.to_class = Class.objects.get(pk=request.session['class_id'])
                    target_student.save()
            except :
                warning = '学生不存在，添加失败！'
    add_form = Add_student()
    return render(request,'add_student.html',locals())

def add_class(request):
    if request.method == 'POST':
        add_form = Add_class(request.POST)
        if add_form.is_valid():
            class_name = add_form.cleaned_data['class_name']
            target_class = Class.objects.filter(class_name=class_name)
            if target_class:
                warning = '您所要创建的班级已存在！'
            else:
                success_message = '创建成功'
                print(request.session['user_name'])
                new_class = Class.objects.create(class_name=class_name,
                                                 create_teacher=request.session['user_name'])
                new_class.save()
    add_form = Add_class()
    return render(request,'add_class.html',locals())
def delate_student(request,id):
    if request.method == 'POST':
        message = '删除成功,请返回学生列表查看'
        student = Student.objects.get(pk=id)
        student.to_class = None
        student.save()
    return render(request,'delate_student.html',locals())
def delate_class(request,id):
    if request.method == 'POST':
        message = '删除成功,请返回班级列表查看'
        del_class = Class.objects.get(pk=id)
        del_class.delete()
    return render(request,'delate_student.html',locals())

backstage/templates/add_class.html
{% extends 'list.html' %}
{% block right_context %}
<div class="col-sm-10">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="glyphicon glyphicon-plus">新增班级</a>
        </div>
        <div class="panel-body">
            {% if warning %}
                <div class="alert alert-warning">{{ warning }}</div>
            {% endif %}
            {% if success_message %}
                <div class="alert alert-success">{{ success_message }}</div>
            {% endif %}
            <form action="." method="post">{% csrf_token %}
                {{ add_form.class_name.label }}{{ add_form.class_name }}
                <input type="submit" value="确认增加" class="btn btn-primary">
            </form>
        </div>
    </div>

</div>



{% endblock %}

backstage/templates/add_student.html
{% extends 'list.html' %}
{% block right_context %}
<div class="col-sm-10">
    <div class="panel panel-default">
        <div class="panel-heading">
            <a class="glyphicon glyphicon-plus">新增学生</a>
        </div>
        <div class="panel-body">
            {% if warning %}
                <div class="alert alert-warning">{{ warning }}</div>
            {% endif %}
            {% if fail_message %}
                <div class="alert alert-danger">{{ fail_message }}</div>
            {% endif %}
            {% if success_message %}
                <div class="alert alert-success">{{ success_message }}</div>
            {% endif %}
            <form action="." method="post">{% csrf_token %}
                {{ add_form.student_name.label }}{{ add_form.student_name }}
                <input type="submit" value="确认增加" class="btn btn-primary">
            </form>
        </div>
    </div>

</div>



{% endblock %}

backstage/templates/class_control.html
{% extends 'list.html' %}
{% block right_context %}
<div class="col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            班级列表
                        </div>
                        <div class="panel-body">
                        <div class="head-form">
                            <form method="post" action="{% url 'backstage:add_class' %}">{% csrf_token %}
                                <div class="text-right">
                                    <button type="submit" class="btn btn-success">新增</button>
                                </div>
                            </form>
                        </div>
                        <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead>
                                <tr>
                                    <th>班级名称</th>
                                    <th>人数</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for context in class_list %}
                                <tr>
                                    <td>{{ context.class_name }}</td>
                                    <td>{{ context.max_student }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="detial/{{ context.id }}" class="btn btn-default">编辑</a><a href="delate/{{ context.id }}" class="btn btn-danger">删除</a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <ul class="pagination" style="float: right;">
                        <li><a href="#">&laquo;</a>
                        </li>
                        <li class="active"><a href="#">1</a>
                        </li>
                        <li><a href="#">2</a>
                        </li>
                        <li><a href="#">3</a>
                        </li>
                        <li><a href="#">4</a>
                        </li>
                        <li><a href="#">5</a>
                        </li>
                        <li><a href="#">&raquo;</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>



{% endblock %}

backstage/templates/class_detial.html
{% extends 'list.html' %}
{% block right_context %}
<div class="col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            学生列表
                        </div>
                        <div class="panel-body">
                        <div class="head-form">
                            <form role="form" class="form-inline" method="post">{% csrf_token %}
                                <div class="form-group">
                                    <input type="text" class="form-control" id="name" placeholder="请输入学生姓名">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-default">开始搜索</button>
                                </div>
                            </form>
                            <form method="post" action="{% url 'backstage:add_student' %}">{% csrf_token %}
                                <div class="text-right">
                                    <button type="submit" class="btn btn-success">新增学生</button>
                                </div>
                            </form>
                        </div>
                        <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead>
                                <tr>
                                    <th>学生姓名</th>
                                    <th>成绩</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for context in student_list %}
                                <tr>
                                    <td>{{ context.name }}</td>
                                    <td>{{ context.max_student }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="delate/{{ context.id }}" class="btn btn-danger">删除</a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <ul class="pagination" style="float: right;">
                        <li><a href="#">&laquo;</a>
                        </li>
                        <li class="active"><a href="#">1</a>
                        </li>
                        <li><a href="#">2</a>
                        </li>
                        <li><a href="#">3</a>
                        </li>
                        <li><a href="#">4</a>
                        </li>
                        <li><a href="#">5</a>
                        </li>
                        <li><a href="#">&raquo;</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>



{% endblock %}

backstage/templates/create_task.html
{% extends 'list.html' %}
{% block title %}发布任务{% endblock %}
{% block right_context %}
    <div class="col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            发布任务
                        </div>
                        <div class="panel-body">
                            <div class="col-md-4 col-md-offset-4">
                                {% if message %}
                                    <div class="alert alert-warning">{{ message }}</div>
                                {% endif %}
                                {% if success %}
                                    <div class="alert alert-success">{{ success }}</div>
                                {% endif %}
                            <form action="." method="post">{% csrf_token %}
                                <div class="form-group">
                                    {{ task_form.title.label }}
                                    {{ task_form.title }}
                                </div>
                                <div class="form-group">
                                    {{ task_form.descriptions.label }}
                                    {{ task_form.descriptions }}
                                </div>
                                <div class="form-group">
                                    {{ task_form.scripts.label }}
                                    {{ task_form.scripts }}
                                </div>
                                <input type="submit" value="一键发布" class="btn btn-primary">
                            </form>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}

backstage/templates/delate_class.html
{% extends 'list.html' %}
{% block right_context %}
    {% if not message %}
    <form action="#" method="post">{% csrf_token %}
        <div class="alert alert-warning col-sm-10">确认删除吗？一旦删除不可撤销。</div>
    <input type="submit" value="确认删除" class="btn btn-primary">
    </form>
        {% else %}
        <div class="alert alert-success col-sm-10">{{ message }}</div>
    {% endif %}

{% endblock %}

backstage/templates/delate_student.html
{% extends 'list.html' %}
{% block right_context %}
    {% if not message %}
    <form action="#" method="post">{% csrf_token %}
        <div class="alert alert-warning col-sm-10">确认删除吗？一旦删除不可撤销。</div>
    <input type="submit" value="确认删除" class="btn btn-primary">
    </form>
        {% else %}
        <div class="alert alert-success col-sm-10">{{ message }}</div>
    {% endif %}

{% endblock %}

backstage/templates/delate_task.html
{% extends 'list.html' %}
{% block right_context %}
    {% if not message %}
    <form action="#" method="post">{% csrf_token %}
        <div class="alert alert-warning col-sm-10">确认删除吗？一旦删除不可撤销。</div>
    <input type="submit" value="确认删除" class="btn btn-primary">
    </form>
        {% else %}
        <div class="alert alert-success col-sm-10">{{ message }}</div>
    {% endif %}

{% endblock %}

backstage/templates/list.html
{% extends 'base.html' %}
{% block title %}后台{% endblock %}
{% block maintext %}
    {% if request.session.user_status == '老师' %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-2">
                    <a href="#" class="list-group-item active"><span class="glyphicon glyphicon-home"></span>后台管理
                    </a>
                    <a href="{% url 'backstage:task_control' %}" class="list-group-item">
                        <span class="glyphicon glyphicon-align-left" aria-hidden="true">
                    </span>任务管理</a>
                    <a href="{% url 'backstage:class_control' %}" class="list-group-item">
                        <span class="glyphicon glyphicon-align-left" aria-hidden="true">
                    </span>班级管理</a>

                </div>
                {% block right_context %}
                    <h2 class="text-center">欢迎来到教师后台</h2>
                {% endblock %}

                    </div>
        </div>
    {% else %}
        <h1>你没有访问权限</h1>
    {% endif %}
{% endblock %}

backstage/templates/task_control.html
{% extends 'list.html' %}
{% block right_context %}
<div class="col-sm-10">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            任务列表
                        </div>
                        <div class="panel-body">
                        <div class="head-form">
                            <form role="form" class="form-inline" method="post">{% csrf_token %}
                                <div class="form-group">
                                    <label for="name">标题</label>
                                    <input type="text" class="form-control" id="name" placeholder="请输入题目的标题">
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-default">开始搜索</button>
                                </div>
                            </form>
                            <form method="post" action="{% url 'backstage:create_task' %}">{% csrf_token %}
                                <div class="text-right">
                                    <button type="submit" class="btn btn-success">新增</button>
                                </div>
                            </form>
                        </div>
                        <div class="table-responsive">
                        <table class="table table-striped ">
                            <thead>
                                <tr>
                                    <th>编号</th>
                                    <th>题目</th>
                                    <th>发布时间</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for context in task_list %}
                                <tr>
                                    <td>{{ context.id }}</td>
                                    <td>{{ context.title }}</td>
                                    <td>{{ context.c_time }}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="detial/{{ context.id }}" class="btn btn-default">编辑</a><a href="delate/{{ context.id }}" class="btn btn-danger">删除</a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <ul class="pagination" style="float: right;">
                        <li><a href="#">&laquo;</a>
                        </li>
                        <li class="active"><a href="#">1</a>
                        </li>
                        <li class="disabled"><a href="#">2</a>
                        </li>
                        <li><a href="#">3</a>
                        </li>
                        <li><a href="#">4</a>
                        </li>
                        <li><a href="#">5</a>
                        </li>
                        <li><a href="#">&raquo;</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>



{% endblock %}

backstage/templates/task_detial.html
{% extends 'list.html' %}
{% block right_context %}
    <div class="col-sm-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                任务详情
            </div>
            <div class="panel-body">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% if success %}
                    <div class="alert alert-success">{{ success }}</div>
                {% endif %}
            <form action="" method="post">{% csrf_token %}
                <div class="form-group">
                    {{ detial_form.title.label }}
                    {{ detial_form.title }}
                </div>
                <div class="form-group">
                    {{ detial_form.descriptions.label }}
                    {{ detial_form.descriptions }}
                </div>
                <div class="form-group">
                    {{ detial_form.scripts.label }}
                    {{ detial_form.scripts }}
                </div>
                {% if not success %}
                    <div><input type="submit" value="确认提交"></div>
                {% endif %}
            </form>
            </div>
        </div>
    </div>
{% endblock %}