blog/urls.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  9:49 下午
# @File    : urls.py
# @Software: PyCharm
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_index, name='index'),
    path('pub/',article_pub,name='pub_article'),
    path('detial/<pk>',blog_detail,name='detial'),
    path('backstage/',blog_control,name='back'),
]

coding/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from front import urls as furls
from login import urls as lurls
from backstage import urls as burls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(furls,namespace='front')),
    path('',include(lurls,namespace='login')),
    path('back/',include(burls,namespace='backstage')),
    path('captcha/',include('captcha.urls')),
    path('mdeditor/',include('mdeditor.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  11:46 下午
# @File    : urls.py
# @Software: PyCharm

from django.urls import path,include
from . import views

app_name = 'login'

urlpatterns = [
    path('login/',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('logout/',views.logout),
]

login/models.py
from django.db import models
from backstage import models as bm

class Student(models.Model):
    gender = (
        ('male', '男'),
        ('female', '女'),
    )
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default='男')
    c_time = models.DateTimeField(auto_now_add=True)
    to_class = models.ForeignKey(bm.Class,on_delete=models.DO_NOTHING,default=None,null=True,blank=True)
    status = models.CharField(max_length=10,editable=False,default='学生')
    def __str__(self):
        return self.name
    class Meta:
        ordering = ['c_time']
        verbose_name = '学生'
        verbose_name_plural = '学生'
class Teacher(models.Model):
    gender = (
        ('male', '男'),
        ('female', '女'),
    )
    name = models.CharField(max_length=128, unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32, choices=gender, default='男')
    c_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10,editable=False, default='老师')
    def __str__(self):
        return self.name

    class Meta:
        ordering = ['c_time']
        verbose_name = '老师'
        verbose_name_plural = '老师'

login/forms.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  10:25 上午
# @File    : forms.py
# @Software: PyCharm
from django import forms
from captcha.fields import CaptchaField

class UserForm(forms.Form):
    username = forms.CharField(label="用户名", max_length=128,widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class':'form-control'}))
    captcha = CaptchaField(label='验证码')

class RegisterForm(forms.Form):
    gender = (
        ('male', "男"),
        ('female', "女"),
    )
    identity = (
        ('student','学生'),
        ('teacher','老师')
    )
    username = forms.CharField(label="用户名", max_length=128, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="确认密码", max_length=256, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="邮箱地址", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    sex = forms.ChoiceField(label='性别', choices=gender)
    status = forms.ChoiceField(label='身份', choices=identity)
    captcha = CaptchaField(label='验证码')

login/views.py
from django.shortcuts import render,redirect
from .forms import *
from .models import *
import hashlib

def hash_code(s,salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest


def login(request):
    request.session['current_url'] = 'index'
    print(request.session['current_url'])
    if request.session.get('is_login',None):
        return redirect('front:index')
    if request.method == "POST":
        login_form = UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = Student.objects.get(name=username)
                if user.password == password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name
                    request.session['user_status'] = user.status
                    return redirect('front:index')
                else:
                    message = "密码不正确！"
            except:
                try:
                    user = Teacher.objects.get(name=username)
                    if user.password == password:
                        request.session['is_login'] = True
                        request.session['user_id'] = user.id
                        request.session['user_name'] = user.name
                        request.session['user_status'] = user.status
                        return redirect('front:index')
                    else:
                        message = "密码不正确！"
                except :
                    message = "用户不存在！"
                message = "用户不存在！"
        return render(request, 'login.html', locals())
    login_form = UserForm()
    return render(request, 'login.html', locals())


def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("front:index")
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            status = register_form.cleaned_data['status']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'register.html', locals())
            else:
                if Student.objects.filter(name=username) or Teacher.objects.filter(name=username):  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'register.html', locals())
                if Student.objects.filter(email=email) or Teacher.objects.filter(email=email):  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'register.html', locals())

                # 当一切都OK的情况下，创建新用户
                print(status)
                if status == 'student':
                    new_user = Student.objects.create()
                else:
                    new_user = Teacher.objects.create()
                new_user.name = username
                new_user.password = password1
                new_user.email = email
                new_user.sex = sex
                new_user.save()
                return redirect('/login/')  # 自动跳转到登录页面
    register_form = RegisterForm()
    return render(request, 'register.html', locals())

def logout(request):
    if not request.session.get('is_login',None):
        return redirect('front:index')
    request.session.flush()
    return redirect('front:index')

login/templates/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block maintext %}
    {% if request.session.is_login %}
        <div class="col-sm-10">
    <a class="list-group-item active">
    任务列表
    </a>
            {% for context in task_list %}
        <a href="editor/{{ context.id }}" class="list-group-item">
            {{ context.title }}
            <div class="text-right">作者：{{ context.author }}&emsp;发布时间：{{ context.c_time }}</div>
    </a>
        {% endfor %}
        <ul class="pagination" style="float: right;">
                        <li><a href="#">&laquo;</a>
                        </li>
                        <li class="active"><a href="#">1</a>
                        </li>
                        <li><a href="#">2</a>
                        </li>
                        <li><a href="#">3</a>
                        </li>
                        <li><a href="#">4</a>
                        </li>
                        <li><a href="#">5</a>
                        </li>
                        <li><a href="#">&raquo;</a>
                        </li>
                    </ul>
        </div>
        <div class="col-sm-2">
            <a href="#" class="list-group-item list-group-item-heading active">排行榜</a>
        </div>
    {% else %}
    <h1 class="text-center">OnlineCoding</h1>
        <p class="text-center">这个网站是专门为学生打造的在线编程平台，现如今仅支持C语言的编程。
        更多功能还在不断完善开发中......
        </p>
        <h3 class="text-center">如果想要使用，请先<a href="{% url 'login:login' %}">登录</a></h3>
    {% endif %}
{% endblock %}

login/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}


{% block maintext %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-login' action="/login/" method="post">
              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎登录</h2>
               <div class="form-group">
                  {{ login_form.username.label_tag }}
                  {{ login_form.username}}
                </div>
                <div class="form-group">
                  {{ login_form.password.label_tag }}
                  {{ login_form.password }}
                </div>
                <div class="form-group">
                  {{ login_form.captcha.errors }}
                  {{ login_form.captcha.label_tag }}
                  {{ login_form.captcha }}
                </div>

              <input type="reset" class="btn btn-default pull-left">
              <input type="submit" class="btn btn-primary pull-right">
          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

login/templates/register.html
{% extends 'base.html' %}
 
{% block title %}注册{% endblock %}
{% block maintext %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="/register/" method="post">
 
              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}
 
              {% csrf_token %}
 
              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                  {{ register_form.username.label_tag }}
                  {{ register_form.username}}
              </div>
              <div class="form-group">
                  {{ register_form.password1.label_tag }}
                  {{ register_form.password1 }}
              </div>
              <div class="form-group">
                  {{ register_form.password2.label_tag }}
                  {{ register_form.password2 }}
              </div>
              <div class="form-group">
                  {{ register_form.email.label_tag }}
                  {{ register_form.email }}
              </div>
              <div class="form-group">
                  {{ register_form.sex.label_tag }}
                  {{ register_form.sex }}
              </div>
              <div class="form-group">
                  {{ register_form.status.label_tag }}
                  {{ register_form.status }}
              </div>
              <div class="form-group">
                  {{ register_form.captcha.errors }}
                  {{ register_form.captcha.label_tag }}
                  {{ register_form.captcha }}
              </div>
 
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
 
          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}