blog/urls.py
# -*- coding: utf-8 -*-
# @Author  : Mr.Xia
# @time    :  9:49 下午
# @File    : urls.py
# @Software: PyCharm
from django.urls import path
from .views import *

app_name = 'blog'
urlpatterns = [
    path('', blog_index, name='index'),
    path('pub/',article_pub,name='pub_article'),
    path('detial/<pk>',blog_detail,name='detial'),
    path('backstage/',blog_control,name='back'),
]

coding/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from front import urls as furls
from login import urls as lurls
from backstage import urls as burls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(furls,namespace='front')),
    path('',include(lurls,namespace='login')),
    path('back/',include(burls,namespace='backstage')),
    path('captcha/',include('captcha.urls')),
    path('mdeditor/',include('mdeditor.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static%}

<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">OnlineCoding</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li {% if request.session.current_url == 'index' %}class="active"{% endif %}><a href="{% url 'front:index' %}">主页</a></li>
              <li {% if request.session.current_url == 'blog' %}class="active"{% endif %}><a href="{% url 'front:blog:index' %}">论坛</a></li>
            <li {% if request.session.current_url == 'blog_editor' %}class="active"{% endif %}><a href="{% url 'front:blog:pub_article' %}">写博客</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.session.is_login %}
                  <li class="dropdown">
                 <a class="dropdown-toggle" data-toggle="dropdown" href="#" target="mainFrame">
                     当前在线：{{ request.session.user_name }}<span class="caret"></span>
                 </a>
                 <ul class="dropdown-menu">
                     {% if request.session.user_status == '老师' %}
                     <li>
                         <a href="{% url 'backstage:index' %}" target="mainFrame">教师后台</a>
                     </li>
                         {% endif %}
                     <li>
                         <a href="#" target="mainFrame">个人中心</a>
                     </li>
                     <li>
                         <a href="#" target="mainFrame">修改密码</a>
                     </li>
                    <li>
                         <a href="{% url 'front:blog:back' %}" target="mainFrame">博客管理</a>
                     </li>
                 </ul>
             </li>
                  <li><a href="/logout/">登出</a></li>
              {% else %}
                  <li><a href="/login/">登录</a></li>
                  <li><a href="/register/">注册</a></li>
              {% endif %}

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    {% block maintext %}{% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
{% block js %}{% endblock %}
</html>

templates/form.html
{% extends 'base.html' %}
{% block title %}
    在线编程
{% endblock %}
{% block maintext %}
            <div class="col-sm-4">
            <div class="text-info page-header"><h3>任务</h3></div>
                <div><h4>题目：{{ task.title }}</h4></div>
                描述：{{ task.descriptions }}
            </div>
            <div class="col-sm-4">
                {% load djangocodemirror_tags %}
<form action="{{ task.id }}" method="post">{% csrf_token %}
    <div class="form-group">
        <div class="text-info page-header"><h3>你的代码</h3></div>

        {{ form.editor }}
    </div>
    <input type="submit" class="btn btn-primary">
</form>

{% codemirror_field_css_assets form.editor %}
{% codemirror_field_js_assets form.editor %}
<script>
    var foo_codemirror = CodeMirror.fromTextArea(
        document.getElementById("id_editor"),
        {{ form.editor|codemirror_parameters }}
    );
</script>
            </div>
            <div class="col-sm-4">
            <div class="text-info page-header"><h3>运行结果</h3></div>
                <div>{{ result }}
                </div></div>
{% endblock %}